name: anime_finder
description: An anime downloader

version: 0.2.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  webfeed: ^0.7.0
  http: ^0.13.4
  transparent_image: ^2.0.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.2
  flutter_launcher_icons: ^0.9.2
  byte_size: ^2.0.0-nullsafety.0
  path: ^1.8.1
  styled_widget: ^0.4.0+3
  cached_network_image: ^3.2.1
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/images/icon.png"