name: anime_finder
description: An anime downloader

version: 0.2.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^3.0.1
  webfeed: ^0.7.0
  http: ^0.13.4
  transparent_image: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  byte_size: ^2.0.0-nullsafety.0
  path: ^1.8.1
  styled_widget: ^0.4.0+3
  cached_network_image: ^3.2.1
  provider: ^6.0.2
  path_provider: ^2.0.10
  ffi: ^2.0.0
  permission_handler: ^10.0.0
  url_launcher: ^6.1.3
  chewie: ^1.3.3
  video_player: ^2.4.4
  expandable: ^5.0.1
  get_storage: ^2.0.3
  flutter_html: ^2.2.1
  flutter_vlc_player: ^7.1.5
  json_annotation: ^4.5.0
  indexed_list_view: ^2.0.2
  visibility_detector: ^0.3.3
  logger: ^1.1.0
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  ffigen: ^6.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/images/icon.png"

ffigen:
  output: 'lib/service/libtorrent_wrapper.dart'
  headers: 
    entry-points:
      - 'lib/dart_torrent/src/dart_torrent.h'
  name: 'LibTorrent'
  description: 'libtorrent-rasterbar dart wrapper'
  functions:
    rename:
      # Removes '_lt' from beginning.
      'lt_(.*)': '$1'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_field, unused_element'