name: anime_finder
description: An anime downloader

version: 0.2.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  google_fonts: ^3.0.1
  webfeed: ^0.7.0
  http: ^0.13.4
  transparent_image: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  path: ^1.8.1
  cached_network_image: ^3.2.1
  path_provider: ^2.0.10
  ffi: ^2.0.0
  url_launcher: ^6.1.3
  expandable: ^5.0.1
  get_storage: ^2.0.3
  flutter_html: ^3.0.0-alpha.5
  flutter_vlc_player: ^7.1.5
  json_annotation: ^4.5.0
  visibility_detector: ^0.3.3
  logger: ^1.1.0
  scrollable_positioned_list: ^0.3.2
  audioplayers: ^1.0.0
  archive: ^3.3.0
  flutter_slidable: ^1.3.0
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.2.0+1
  palette_generator: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  ffigen: ^6.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - google_fonts/

flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  background_image: "assets/images/splashscreen.png"
  android_12:
    image: "assets/images/splashscreen.png"
    color: "#42a5f5"
    color_dart: "#042a49"
ffigen:
  output: 'lib/service/libtorrent_wrapper.dart'
  headers: 
    entry-points:
      - 'lib/dart_torrent/src/dart_torrent.h'
  name: 'LibTorrent'
  description: 'libtorrent-rasterbar dart wrapper'
  functions:
    rename:
      # Removes '_lt' from beginning.
      'lt_(.*)': '$1'
  preamble: '// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_field, unused_element'