// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_field, unused_element
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// libtorrent-rasterbar dart wrapper
class LibTorrent {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibTorrent(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibTorrent.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> print_queue_last() {
    return _print_queue_last();
  }

  late final _print_queue_lastPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'lt_print_queue_last');
  late final _print_queue_last =
      _print_queue_lastPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void pop_print_queue() {
    return _pop_print_queue();
  }

  late final _pop_print_queuePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('lt_pop_print_queue');
  late final _pop_print_queue =
      _pop_print_queuePtr.asFunction<void Function()>();

  void add_torrent(
    ffi.Pointer<ffi.Char> magnet_url,
    ffi.Pointer<ffi.Char> save_path,
    bool is_torrent_file,
  ) {
    return _add_torrent(
      magnet_url,
      save_path,
      is_torrent_file,
    );
  }

  late final _add_torrentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Bool)>>('lt_add_torrent');
  late final _add_torrent = _add_torrentPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, bool)>();

  void init_session(
    ffi.Pointer<ffi.Char> db_path,
  ) {
    return _init_session(
      db_path,
    );
  }

  late final _init_sessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'lt_init_session');
  late final _init_session =
      _init_sessionPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Void> get_torrent_vec() {
    return _get_torrent_vec();
  }

  late final _get_torrent_vecPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'lt_get_torrent_vec');
  late final _get_torrent_vec =
      _get_torrent_vecPtr.asFunction<ffi.Pointer<ffi.Void> Function()>();

  int torrent_vec_size(
    ffi.Pointer<ffi.Void> p_torrent_vec,
  ) {
    return _torrent_vec_size(
      p_torrent_vec,
    );
  }

  late final _torrent_vec_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_vec_size');
  late final _torrent_vec_size =
      _torrent_vec_sizePtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> torrent_handle_at(
    ffi.Pointer<ffi.Void> p_torrent_vec,
    int index,
  ) {
    return _torrent_handle_at(
      p_torrent_vec,
      index,
    );
  }

  late final _torrent_handle_atPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>, ffi.Size)>>('lt_torrent_handle_at');
  late final _torrent_handle_at = _torrent_handle_atPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)>();

  ffi.Pointer<ffi.Char> torrent_name(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_name(
      p_torrent_handle,
    );
  }

  late final _torrent_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Void>)>>('lt_torrent_name');
  late final _torrent_name = _torrent_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> torrent_save_path(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_save_path(
      p_torrent_handle,
    );
  }

  late final _torrent_save_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Void>)>>('lt_torrent_save_path');
  late final _torrent_save_path = _torrent_save_pathPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> torrent_state(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_state(
      p_torrent_handle,
    );
  }

  late final _torrent_statePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Void>)>>('lt_torrent_state');
  late final _torrent_state = _torrent_statePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>();

  double torrent_progress(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_progress(
      p_torrent_handle,
    );
  }

  late final _torrent_progressPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_progress');
  late final _torrent_progress =
      _torrent_progressPtr.asFunction<double Function(ffi.Pointer<ffi.Void>)>();

  int torrent_file_size(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_file_size(
      p_torrent_handle,
    );
  }

  late final _torrent_file_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_file_size');
  late final _torrent_file_size =
      _torrent_file_sizePtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  int torrent_download_rate(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_download_rate(
      p_torrent_handle,
    );
  }

  late final _torrent_download_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_download_rate');
  late final _torrent_download_rate = _torrent_download_ratePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  bool torrent_paused(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_paused(
      p_torrent_handle,
    );
  }

  late final _torrent_pausedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_paused');
  late final _torrent_paused =
      _torrent_pausedPtr.asFunction<bool Function(ffi.Pointer<ffi.Void>)>();

  bool torrent_finished(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_finished(
      p_torrent_handle,
    );
  }

  late final _torrent_finishedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_finished');
  late final _torrent_finished =
      _torrent_finishedPtr.asFunction<bool Function(ffi.Pointer<ffi.Void>)>();

  void pause_torrent(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _pause_torrent(
      p_torrent_handle,
    );
  }

  late final _pause_torrentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'lt_pause_torrent');
  late final _pause_torrent =
      _pause_torrentPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void resume_torrent(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _resume_torrent(
      p_torrent_handle,
    );
  }

  late final _resume_torrentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'lt_resume_torrent');
  late final _resume_torrent =
      _resume_torrentPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void remove_torrent(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _remove_torrent(
      p_torrent_handle,
    );
  }

  late final _remove_torrentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'lt_remove_torrent');
  late final _remove_torrent =
      _remove_torrentPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> torrent_files(
    ffi.Pointer<ffi.Void> p_torrent_handle,
  ) {
    return _torrent_files(
      p_torrent_handle,
    );
  }

  late final _torrent_filesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>)>>('lt_torrent_files');
  late final _torrent_files = _torrent_filesPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  int torrent_num_files(
    ffi.Pointer<ffi.Void> p_torrent_files,
  ) {
    return _torrent_num_files(
      p_torrent_files,
    );
  }

  late final _torrent_num_filesPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
          'lt_torrent_num_files');
  late final _torrent_num_files =
      _torrent_num_filesPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> file_info_at(
    ffi.Pointer<ffi.Void> p_torrent_files,
    int index,
  ) {
    return _file_info_at(
      p_torrent_files,
      index,
    );
  }

  late final _file_info_atPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>, ffi.Int64)>>('lt_file_info_at');
  late final _file_info_at = _file_info_atPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)>();

  ffi.Pointer<ffi.Char> file_name(
    ffi.Pointer<ffi.Void> p_torrent_file_info,
  ) {
    return _file_name(
      p_torrent_file_info,
    );
  }

  late final _file_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Void>)>>('lt_file_name');
  late final _file_name = _file_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> file_path(
    ffi.Pointer<ffi.Void> p_torrent_file_info,
  ) {
    return _file_path(
      p_torrent_file_info,
    );
  }

  late final _file_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Void>)>>('lt_file_path');
  late final _file_path = _file_pathPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>)>();

  int file_size(
    ffi.Pointer<ffi.Void> p_torrent_file_info,
  ) {
    return _file_size(
      p_torrent_file_info,
    );
  }

  late final _file_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<ffi.Void>)>>(
          'lt_file_size');
  late final _file_size =
      _file_sizePtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();
}

class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi
          .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

const int __WORDSIZE = 64;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int USER_ADDR_NULL = 0;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int true1 = 1;

const int false1 = 0;

const int __bool_true_false_are_defined = 1;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int NULL = 0;
